<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-12ATVB7" failures="1" tests="1" name="Default test(failed)(failed)" time="0.125" errors="0" timestamp="2023-05-06T18:22:12 IST">
  <testcase classname="Testng_advantages.FailedTC" name="TC3" time="0.023">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Testng_advantages.FailedTC.TC3(FailedTC.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC3 -->
  <testcase classname="Testng_advantages.FailedTC" name="TC2" time="0.0">
    <ignored/>
  </testcase> <!-- TC2 -->
  <testcase classname="Testng_advantages.FailedTC" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
</testsuite> <!-- Default test(failed)(failed) -->
